# The list of words was created using ChatGPT 3.5.
# The list contains only 6 letter words for changing the base game:
# instead of creating a picture for fails, a picture is generated for 
# correct answers.
word_list = [
    "Potato",
    "Garden",
    "Yellow",
    "Velvet",
    "Window",
    "Guitar",
    "Canyon",
    "Tunnel",
    "Socket",
    "Bonnet",
    "Jungle",
    "Pencil",
    "Anchor",
    "Zipper",
    "Spirit",
    "Sizzle",
    "Forest",
    "Marble",
    "Fossil",
    "Banana",
    "Castle",
    "Kidney",
    "Rocket",
    "Pillow",
    "Arctic",
    "Wisely",
    "Banner",
    "Symbol",
    "Voyage",
    "Plunge",
    "Zephyr",
    "Muffin",
    "Sphere",
    "Bronze",
    "Cheese",
    "Rhythm",
    "Exotic",
    "Walnut"
]
